stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/X_train.pkl
      - data/processed/X_test.pkl
      - data/processed/y_train.pkl
      - data/processed/y_test.pkl
      - data/processed/tfidf_vectorizer.pkl

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/X_train.pkl
      - data/processed/y_train.pkl
      - data/processed/tfidf_vectorizer.pkl
    outs:
      - models/spam_classifier.pkl
      - models/tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/spam_classifier.pkl
      - models/tfidf_vectorizer.pkl
      - data/raw/test.csv
    
